name: connectivity_plus
description: Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
version: 5.0.1
publish_to: none
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/connectivity_plus/connectivity_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/connectivity_plus

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.connectivity
        pluginClass: ConnectivityPlugin
      ios:
        pluginClass: ConnectivityPlusPlugin
      linux:
        dartPluginClass: ConnectivityPlusLinuxPlugin
      macos:
        pluginClass: ConnectivityPlugin
      web:
        pluginClass: ConnectivityPlusWebPlugin
        fileName: src/connectivity_plus_web.dart
      windows:
        pluginClass: ConnectivityPlusWindowsPlugin

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  connectivity_plus_platform_interface: 
    git: https://github.com/kumsumit/connectivity_plus_platform_interface.git
  js: ^0.6.4
  meta: ^1.9.1
  nm: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  dbus: ^0.7.8
  flutter_lints: 
    git: https://github.com/kumsumit/flutter_lints.git
  mockito: ^5.4.2
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git
  test: ^1.22.0
